#!/bin/csh
# -*- shell-script -*-
########################################################################
#  This is the system wide source file for setting up
#  modules:
#
########################################################################

set MY_NAME="/opt/sw/lmod/lmod/init/cshrc"



if ( ! $?MODULEPATH_ROOT ) then
    if ( $?USER) then
        setenv USER $LOGNAME
    endif

    set UNAME = `uname`
    setenv LMOD_sys    $UNAME

    setenv LMOD_arch   `uname -m`
    if ( "x$UNAME" == xAIX ) then
        setenv LMOD_arch   rs6k
    endif

    setenv TARG_TITLE_BAR_PAREN " "
    setenv LMOD_FULL_SETTARG_SUPPORT no
    setenv LMOD_SETTARG_CMD     :
    setenv LMOD_COLORIZE        yes
    setenv LMOD_PREPEND_BLOCK   normal
    setenv MODULEPATH_ROOT      "/opt/sw/modulefiles"
    setenv MODULEPATH           `/opt/sw/lmod/lmod/libexec/addto --append MODULEPATH $MODULEPATH_ROOT/$LMOD_sys $MODULEPATH_ROOT/Core`
    setenv MODULEPATH           `/opt/sw/lmod/lmod/libexec/addto --append MODULEPATH /opt/sw/lmod/lmod/modulefiles/Core`
    setenv MODULESHOME          "/opt/sw/lmod/lmod"
    setenv BASH_ENV             "$MODULESHOME/init/bash"

    setenv LMOD_AVAIL_STYLE     "grouped"

    #
    # If MANPATH is empty, Lmod is adding a trailing ":" so that
    # the system MANPATH will be found
    if ( ! $?MANPATH ) then
      setenv MANPATH :
    endif
    setenv MANPATH `/opt/sw/lmod/lmod/libexec/addto MANPATH /opt/sw/lmod/lmod/share/man`

endif

if ( -f  /opt/sw/lmod/lmod/init/csh  ) then
  source /opt/sw/lmod/lmod/init/csh
endif

# Local Variables:
# mode: shell-script
# indent-tabs-mode: nil
# End:

